name: poslan

service:
  type: NodePort
  nodePort: ""
  port: 8080

deployment:
  replicaCount: 1
  port: 8080

  image:
    private: true
    repository: adrianpksw
    tag: stage
    pullPolicy: Always
    volumeMounts:
      configSecretMountPath: /configs
    volumes:
      configSecretMountName: config-volume
      configSecretName: poslan-config
  container:
    # These are example values.
    # The keys are not real.
    # These kind of values should not be control versioned.
    env:
      - name: POSLAN_SERVER_PORT
        value: "8080"
      - name: POSLAN_LOG_LEVEL
        value: "debug"
      - name: PROVIDER_NAME_1
        value: "amazon"
      - name: PROVIDER_TYPE_1
        value: "amazon-ses"
      - name: PROVIDER_ENABLED_1
        value: "true"
      - name: PROVIDER_TESTONLY_1
        value: "false"
      - name: PROVIDER_SENDER_NAME_1
        value: "SendMailTest"
      - name: PROVIDER_SENDER_EMAIL_1
        value: "sendmailtest@sharkslasers.com"
      - name: PROVIDER_NAME_2
        value: "sendgrid"
      - name: PROVIDER_TYPE_2
        value: "sendgrid"
      - name: PROVIDER_ENABLED_2
        value: "true"
      - name: PROVIDER_TESTONLY_2
        value: "false"
      - name: PROVIDER_SENDER_NAME_2
        value: "SendMailTest"
      - name: PROVIDER_SENDER_EMAIL_2
        value: "sendmailtest@sharkslasers.com"
      - name: AWS_ACCESS_KEY_ID
        value: "BKIAHI2FF3AHO1ZMJEXJ"
      - name: AWS_SECRET_KEY
        value: "2BiWmd2Hdgmk2rR4plG332bHwvLGiFOcxLLtDy1g"
      - name: SENDGRID_API_KEY
        value: "h021spSdgTNABAha22u633kd8l49b2a-lL3Bo0YX2n3"
