apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service-lab-stage
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/proxy-body-size: "40m"
spec:
  tls:
    - secretName: ingress-tls-v2-next
      hosts:
        - 35.198.108.167
  rules:
    - host: 35.198.108.167
      http:
        paths:
          - path: /poslan
            backend:
              serviceName: poslan
              servicePort: 8080