app:
  serverPort: 8080
  logLevel: "debug"

mailer:
  provider:
    - name: "amazon"
      type: "amazon-ses"
      enabled: true
      apiKey: am1

    - name: "sendgrid"
      type: "sendgrid"
      enabled: true
      apiKey: sg1
