app:
  serverPort: 8080
  logLevel: "debug"

mailer:
  provider:
    - name: "amazon-one"
      type: "ses"
      enabled: true
      apiKey: am1

    - name: "sendgrid-one"
      type: "sendgrid"
      enabled: true
      apiKey: sg1
