app:
  serverPort: 8080
  logLevel: "debug"

mailer:
  provider:
    - name: "amazon"
      type: "amazon-ses"
      enabled: true
      idKey: "-"
      apiKey: "-"
      sender:
        name: sender
        email: sendmailtest@sharkslasers.com

    - name: "sendgrid"
      type: "sendgrid"
      enabled: true
      idKey: "-"
      apiKey: "-"
      sender:
        name: sender
        email: sendmailtest@sharkslasers.com
